mongo:
  image: aashreys/mongo-auth
  volumes:
    - $HOME/data/mongodb:/data/db
  restart: always
  ports:
    - "127.0.0.1:27017"
  environment:
    AUTH: "yes"
    MONGODB_ADMIN_USER: ${BIEN_MONGO_USER}
    MONGODB_ADMIN_PASS: ${BIEN_MONGO_PWD}
    MONGODB_APPLICATION_DATABASE: bienusers
    MONGODB_APPLICATION_USER: ${BIEN_MONGO_USER}
    MONGODB_APPLICATION_PASS: ${BIEN_MONGO_PWD}

redis:
  image: redis
  restart: always
  volumes:
    - $HOME/data/redis:/data
  command:  redis-server --appendonly yes

api:
  build: .
  ports:
    - "8876:8876"
  links:
    - mongo
    - redis
  restart: always
  environment:
    BIEN_API_KEY: ${BIEN_API_KEY}
    BIEN_MONGO_USER: ${BIEN_MONGO_USER}
    BIEN_MONGO_PWD: ${BIEN_MONGO_PWD}
